### PR TITLE
WIP Preparing release v3.2.0 with SonarQube v7.9 compatibility

### LINKED ISSUE #82: Doesn't work with Sonar 7.5
Plugin doesn't work with SonarQube 7.5

`2019.05.17 10:11:54 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Unable to load component class com.qualinsight.plugins.sonarqube.badges.ws.BadgesWebService
        at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:65)
...
Caused by: java.lang.IllegalStateException: Unable to load component class com.qualinsight.plugins.sonarqube.badges.ws.gate.QualityGateBadgeAction
        at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:65)
...
`

### PR DESCRIPTION
**Pull request by gschafra**
- Fixes QualInsight/qualinsight-plugins-sonarqube-badges#82
- SonarQube v7.9 only supports Java v11

### CODE REVIEW

**Comment by daj** [comment]
Do you have plans to release a version of SVG Badges that is compatible with the newer Sonar versions?  It would be great if you do as my code coverage badges just stopped working after we upgraded our Sonar instance... :-)

**Comment by gschafra** [comment]
> 
> 
> Do you have plans to release a version of SVG Badges that is compatible with the newer Sonar versions? It would be great if you do as my code coverage badges just stopped working after we upgraded our Sonar instance... :-)

@daj I really want to try, honestly. But I'm currently struggling with my intelectual and time capacity 😭 . Maybe it will happen within the next  3 months, sometime around Easter 🐰 , sorry. But in the meantime, you can take look on @maxiko's fork, which just released a v7/8 version (see https://github.com/maxiko/qualinsight-plugins-sonarqube-badges/releases)

**Comment by daj** [comment]
Nice tip, I'll take a look at that fork - thanks!

**Comment by gschafra** [comment]
Dropping this PR/branch in favour of new v8.9.6 LTS one

**Pull request closed without merging**
